Warning: no access to tty (Bad file descriptor).
Thus no job control in this shell.
Fri Aug 12 08:16:38 GMT 2022
jlab.py:30: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  elif dashinfo is not '0':
jlab.py:33: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if dashinfo is not '0':
[I 2022-08-12 08:17:09.459 ServerApp] jupyterlab | extension was successfully linked.
[W 2022-08-12 08:17:09.474 NotebookApp] 'password' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[I 2022-08-12 08:17:09.482 ServerApp] nbclassic | extension was successfully linked.
[I 2022-08-12 08:17:14.689 ServerApp] notebook_shim | extension was successfully linked.
[I 2022-08-12 08:17:15.294 ServerApp] notebook_shim | extension was successfully loaded.
[I 2022-08-12 08:17:15.295 LabApp] JupyterLab extension loaded from /home1/datahome/mdemol/.miniconda3/envs/m2env/lib/python3.8/site-packages/jupyterlab
[I 2022-08-12 08:17:15.295 LabApp] JupyterLab application directory is /home1/datahome/mdemol/.miniconda3/envs/m2env/share/jupyter/lab
[I 2022-08-12 08:17:15.299 ServerApp] jupyterlab | extension was successfully loaded.
[I 2022-08-12 08:17:15.449 ServerApp] nbclassic | extension was successfully loaded.
[I 2022-08-12 08:17:15.449 ServerApp] Serving notebooks from local directory: /home1/datahome/mdemol
[I 2022-08-12 08:17:15.449 ServerApp] Jupyter Server 1.16.0 is running at:
[I 2022-08-12 08:17:15.449 ServerApp] http://r2i0n18:8877/lab
[I 2022-08-12 08:17:15.449 ServerApp]  or http://127.0.0.1:8877/lab
[I 2022-08-12 08:17:15.449 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 2022-08-12 08:19:00.020 ServerApp] 404 GET /apple-touch-icon-precomposed.png (10.148.1.145) 127.29ms referer=None
[W 2022-08-12 08:19:00.919 ServerApp] 404 GET /apple-touch-icon.png (10.148.1.145) 1.01ms referer=None
[I 2022-08-12 08:19:03.746 LabApp] Build is up to date
[W 2022-08-12 08:19:08.318 ServerApp] Notebook m2_2022/sandbox/diag_pdf_ind.ipynb is not trusted
[I 2022-08-12 08:19:10.968 ServerApp] Kernel started: 4bbffea0-e14a-4ec5-8251-cc6350c16ac8
[I 2022-08-12 08:19:11.223 ServerApp] Kernel started: fefd0dd4-1a37-4b72-8cab-91e3d1b3c32e
[I 2022-08-12 08:19:14.861 ServerApp] Kernel started: a86a509c-88ea-490c-9cb2-7a0267114c55
[I 2022-08-12 08:19:15.144 ServerApp] Kernel started: dd9889f9-54b5-4014-a95f-9758ae886487
[I 2022-08-12 08:19:16.310 ServerApp] Kernel started: 66be769d-c0c4-4f6c-90b2-b12272b9b510
readline: /etc/inputrc: line 19: term: unknown variable name
readline: /etc/inputrc: line 19: term: unknown variable name
readline: /etc/inputrc: line 19: term: unknown variable name
[IPKernelApp] ERROR | No such comm target registered: jupyter.widget.control
[IPKernelApp] WARNING | No such comm: c49bb08a-b8b1-4602-9609-d9aa23adde4c
readline: /etc/inputrc: line 19: term: unknown variable name
readline: /etc/inputrc: line 19: term: unknown variable name
[IPKernelApp] ERROR | No such comm target registered: jupyter.widget.control
[IPKernelApp] WARNING | No such comm: 7ccbc316-55b9-4dfb-80ab-aa892b284a12
[IPKernelApp] ERROR | No such comm target registered: jupyter.widget.control
[IPKernelApp] WARNING | No such comm: 7d604ab5-c529-4d73-985e-fe0eb8f8082a
[IPKernelApp] ERROR | No such comm target registered: jupyter.widget.control
[IPKernelApp] WARNING | No such comm: 74fc38d5-8bf3-4b78-b41b-163d00526fda
[IPKernelApp] ERROR | No such comm target registered: jupyter.widget.control
[IPKernelApp] WARNING | No such comm: b1cacb8b-0bc9-47b1-b4f1-0f65403f68f7
[I 2022-08-12 08:21:10.583 ServerApp] Saving file at /m2_2022/sandbox/animation.ipynb
[I 2022-08-12 08:23:12.664 ServerApp] Saving file at /m2_2022/sandbox/animation.ipynb
[I 2022-08-12 08:25:14.815 ServerApp] Saving file at /m2_2022/sandbox/animation.ipynb
[I 2022-08-12 08:31:17.445 ServerApp] Saving file at /m2_2022/sandbox/animation.ipynb
[I 2022-08-12 08:33:20.954 ServerApp] Saving file at /m2_2022/sandbox/animation.ipynb
[I 2022-08-12 08:35:24.135 ServerApp] Saving file at /m2_2022/sandbox/animation.ipynb
[I 2022-08-12 08:39:27.128 ServerApp] Saving file at /m2_2022/sandbox/animation.ipynb
[I 2022-08-12 08:41:30.247 ServerApp] Saving file at /m2_2022/sandbox/animation.ipynb
[I 2022-08-12 08:43:33.516 ServerApp] Saving file at /m2_2022/sandbox/animation.ipynb
[I 2022-08-12 08:45:37.182 ServerApp] Saving file at /m2_2022/sandbox/animation.ipynb
[I 2022-08-12 08:47:40.516 ServerApp] Saving file at /m2_2022/sandbox/animation.ipynb
[I 2022-08-12 08:49:43.746 ServerApp] Saving file at /m2_2022/sandbox/animation.ipynb
[I 2022-08-12 08:51:47.169 ServerApp] Saving file at /m2_2022/sandbox/animation.ipynb
[I 2022-08-12 08:53:51.320 ServerApp] Saving file at /m2_2022/sandbox/animation.ipynb
[I 2022-08-12 08:55:54.568 ServerApp] Saving file at /m2_2022/sandbox/animation.ipynb
/home1/datahome/mdemol/.miniconda3/envs/m2env/lib/python3.8/contextlib.py:120: UserWarning: Creating scratch directories is taking a surprisingly long time. This is often due to running workers on a network file system. Consider specifying a local-directory to point workers to write scratch data to a local disk.
  next(self.gen)
/home1/datahome/mdemol/.miniconda3/envs/m2env/lib/python3.8/contextlib.py:120: UserWarning: Creating scratch directories is taking a surprisingly long time. This is often due to running workers on a network file system. Consider specifying a local-directory to point workers to write scratch data to a local disk.
  next(self.gen)
/home1/datahome/mdemol/.miniconda3/envs/m2env/lib/python3.8/contextlib.py:120: UserWarning: Creating scratch directories is taking a surprisingly long time. This is often due to running workers on a network file system. Consider specifying a local-directory to point workers to write scratch data to a local disk.
  next(self.gen)
/home1/datahome/mdemol/.miniconda3/envs/m2env/lib/python3.8/contextlib.py:120: UserWarning: Creating scratch directories is taking a surprisingly long time. This is often due to running workers on a network file system. Consider specifying a local-directory to point workers to write scratch data to a local disk.
  next(self.gen)
/home1/datahome/mdemol/.miniconda3/envs/m2env/lib/python3.8/contextlib.py:120: UserWarning: Creating scratch directories is taking a surprisingly long time. This is often due to running workers on a network file system. Consider specifying a local-directory to point workers to write scratch data to a local disk.
  next(self.gen)
/home1/datahome/mdemol/.miniconda3/envs/m2env/lib/python3.8/contextlib.py:120: UserWarning: Creating scratch directories is taking a surprisingly long time. This is often due to running workers on a network file system. Consider specifying a local-directory to point workers to write scratch data to a local disk.
  next(self.gen)
[I 2022-08-12 09:01:57.927 ServerApp] Saving file at /m2_2022/sandbox/animation.ipynb
[I 2022-08-12 09:05:22.050 ServerApp] Starting buffering for 4bbffea0-e14a-4ec5-8251-cc6350c16ac8:8f9799b8-3802-4504-8b63-4db8b76ec8b1
[I 2022-08-12 09:06:39.404 ServerApp] Kernel started: 81258831-5f98-4d35-802f-5362b7af0442
readline: /etc/inputrc: line 19: term: unknown variable name
[IPKernelApp] ERROR | No such comm target registered: jupyter.widget.control
[IPKernelApp] WARNING | No such comm: ebde844d-e157-4bce-b178-1b11ad27262d
[I 2022-08-12 09:07:54.887 ServerApp] Saving file at /m2_2022/sandbox/diag_lonlatphi.ipynb
[I 2022-08-12 09:10:57.254 ServerApp] Saving file at /m2_2022/sandbox/diag_lonlat.ipynb
[I 2022-08-12 09:12:47.500 ServerApp] Kernel restarted: 81258831-5f98-4d35-802f-5362b7af0442
[I 2022-08-12 09:12:47.625 ServerApp] Starting buffering for 81258831-5f98-4d35-802f-5362b7af0442:8dd64d2d-bee5-4880-99b6-25b0d330d999
[I 2022-08-12 09:12:47.695 ServerApp] Restoring connection for 81258831-5f98-4d35-802f-5362b7af0442:8dd64d2d-bee5-4880-99b6-25b0d330d999
readline: /etc/inputrc: line 19: term: unknown variable name
[IPKernelApp] ERROR | No such comm target registered: jupyter.widget.control
[IPKernelApp] WARNING | No such comm: cb213db2-dc35-414d-a11b-347d890ce3fb
[I 2022-08-12 09:13:52.649 ServerApp] Kernel started: ce66ad7c-ac32-456a-ae88-464d15e0a83e
readline: /etc/inputrc: line 19: term: unknown variable name
[IPKernelApp] ERROR | No such comm target registered: jupyter.widget.control
[IPKernelApp] WARNING | No such comm: 84a37c1f-7773-4458-b3c2-a879683f7fe8
[I 2022-08-12 09:14:46.688 ServerApp] Saving file at /m2_2022/sandbox/diag_lonlat.ipynb
[I 2022-08-12 09:18:37.239 ServerApp] Saving file at /m2_2022/sandbox/diag_lonlat.ipynb
[I 2022-08-12 09:22:29.815 ServerApp] Saving file at /m2_2022/sandbox/diag_lonlat.ipynb
[I 2022-08-12 09:37:15.752 ServerApp] Starting buffering for 81258831-5f98-4d35-802f-5362b7af0442:8dd64d2d-bee5-4880-99b6-25b0d330d999
[I 2022-08-12 09:37:15.752 ServerApp] Starting buffering for ce66ad7c-ac32-456a-ae88-464d15e0a83e:b7d619d8-12d4-48aa-b455-4abf5a646bae
[I 2022-08-12 09:37:15.753 ServerApp] Starting buffering for fefd0dd4-1a37-4b72-8cab-91e3d1b3c32e:5bea81ec-227d-4324-8bfd-998592035fde
[I 2022-08-12 09:37:15.754 ServerApp] Starting buffering for a86a509c-88ea-490c-9cb2-7a0267114c55:d1aabe51-df02-4eab-9a2d-5d31fcc41591
[I 2022-08-12 09:37:15.755 ServerApp] Starting buffering for dd9889f9-54b5-4014-a95f-9758ae886487:d3ebb5d5-b16f-41ed-9cc9-2fc2d6520852
[I 2022-08-12 09:37:15.755 ServerApp] Starting buffering for 66be769d-c0c4-4f6c-90b2-b12272b9b510:e223dd06-f933-4452-9b9a-b0893860295c
[I 2022-08-12 09:40:55.876 ServerApp] Restoring connection for dd9889f9-54b5-4014-a95f-9758ae886487:d3ebb5d5-b16f-41ed-9cc9-2fc2d6520852
[I 2022-08-12 09:40:57.866 ServerApp] Restoring connection for a86a509c-88ea-490c-9cb2-7a0267114c55:d1aabe51-df02-4eab-9a2d-5d31fcc41591
[IPKernelApp] ERROR | No such comm target registered: jupyter.widget.control
[IPKernelApp] WARNING | No such comm: 832a372a-819e-43a3-8819-8f70c518a112
[IPKernelApp] ERROR | No such comm target registered: jupyter.widget.control
[IPKernelApp] WARNING | No such comm: 39685980-3725-4880-aa6d-7b8bb253778e
[I 2022-08-12 09:41:02.804 ServerApp] Restoring connection for ce66ad7c-ac32-456a-ae88-464d15e0a83e:b7d619d8-12d4-48aa-b455-4abf5a646bae
[IPKernelApp] ERROR | No such comm target registered: jupyter.widget.control
[IPKernelApp] WARNING | No such comm: d1a469e4-a068-4a89-8528-1444dedeb1eb
[IPKernelApp] ERROR | No such comm target registered: jupyter.widget.control
[IPKernelApp] WARNING | No such comm: bf71ce6b-3366-46aa-9edd-f752fd28cccc
[I 2022-08-12 09:41:10.300 ServerApp] Restoring connection for 81258831-5f98-4d35-802f-5362b7af0442:8dd64d2d-bee5-4880-99b6-25b0d330d999
[IPKernelApp] ERROR | No such comm target registered: jupyter.widget.control
[IPKernelApp] WARNING | No such comm: ba3c1b71-006f-4fe7-b339-b8bf8b62f7a4
[IPKernelApp] ERROR | No such comm target registered: jupyter.widget.control
[IPKernelApp] WARNING | No such comm: c58e6dbd-d9dc-4b30-b070-7bb77d97adfc
[I 2022-08-12 09:49:36.027 ServerApp] Saving file at /m2_2022/sandbox/diag_lonlat.ipynb
[I 2022-08-12 09:49:55.565 ServerApp] Starting buffering for 81258831-5f98-4d35-802f-5362b7af0442:8dd64d2d-bee5-4880-99b6-25b0d330d999
[I 2022-08-12 09:52:10.758 ServerApp] Starting buffering for a86a509c-88ea-490c-9cb2-7a0267114c55:d1aabe51-df02-4eab-9a2d-5d31fcc41591
[I 2022-08-12 09:52:19.427 ServerApp] Starting buffering for ce66ad7c-ac32-456a-ae88-464d15e0a83e:b7d619d8-12d4-48aa-b455-4abf5a646bae
[I 2022-08-12 09:53:43.735 ServerApp] Saving file at /m2_2022/sandbox/diag_lonlatphi.ipynb
[I 2022-08-12 09:57:56.086 ServerApp] Saving file at /m2_2022/sandbox/diag_lonlatphi.ipynb
[IPKernelApp] ERROR | No such comm target registered: jupyter.widget.control
[IPKernelApp] WARNING | No such comm: 7dfb736b-331c-4697-8c5c-cd4933f820d0
[I 2022-08-12 10:01:55.842 ServerApp] Saving file at /m2_2022/sandbox/diag_lonlatphi.ipynb
[I 2022-08-12 10:05:56.970 ServerApp] Saving file at /m2_2022/sandbox/diag_lonlatphi.ipynb
[I 2022-08-12 10:34:24.551 ServerApp] Copying m2_2022/sandbox/zarr_stat_dist.ipynb to /m2_2022/sandbox
[I 2022-08-12 10:34:54.046 ServerApp] Kernel started: dbceacae-2852-4a3f-80ee-0c8cc011c227
readline: /etc/inputrc: line 19: term: unknown variable name
[IPKernelApp] ERROR | No such comm target registered: jupyter.widget.control
[IPKernelApp] WARNING | No such comm: 217bf2c9-dea1-4f82-bb14-2651a7f9a989
[I 2022-08-12 10:37:04.948 ServerApp] Saving file at /m2_2022/sandbox/zarr_stat_time.ipynb
[W 2022-08-12 10:41:02.771 ServerApp] WebSocket ping timeout after 119706 ms.
[W 2022-08-12 10:41:03.244 ServerApp] WebSocket ping timeout after 119692 ms.
[W 2022-08-12 10:41:06.925 ServerApp] WebSocket ping timeout after 119954 ms.
[I 2022-08-12 10:41:08.245 ServerApp] Starting buffering for 81258831-5f98-4d35-802f-5362b7af0442:6a619003-7c85-42ad-a0ed-88b13ed678ac
[W 2022-08-12 10:41:10.492 ServerApp] WebSocket ping timeout after 119965 ms.
[W 2022-08-12 10:41:12.074 ServerApp] WebSocket ping timeout after 119962 ms.
[W 2022-08-12 10:41:12.106 ServerApp] WebSocket ping timeout after 119963 ms.
[W 2022-08-12 10:41:14.081 ServerApp] WebSocket ping timeout after 119941 ms.
[I 2022-08-12 10:41:17.107 ServerApp] Starting buffering for fefd0dd4-1a37-4b72-8cab-91e3d1b3c32e:65cce79a-47d7-427c-be03-76f2ac1084d8
[I 2022-08-12 10:41:19.084 ServerApp] Starting buffering for 66be769d-c0c4-4f6c-90b2-b12272b9b510:307a1872-eda3-4ba8-9cdd-2819d29d9a35
[W 2022-08-12 10:41:24.983 ServerApp] WebSocket ping timeout after 119962 ms.
[W 2022-08-12 10:41:25.878 ServerApp] WebSocket ping timeout after 119945 ms.
[I 2022-08-12 10:41:29.984 ServerApp] Starting buffering for dbceacae-2852-4a3f-80ee-0c8cc011c227:2f28c86c-3fce-4d7d-8964-0ccd766721eb
[I 2022-08-12 10:41:30.880 ServerApp] Starting buffering for dd9889f9-54b5-4014-a95f-9758ae886487:d3ebb5d5-b16f-41ed-9cc9-2fc2d6520852
[IPKernelApp] ERROR | No such comm target registered: jupyter.widget.control
[IPKernelApp] WARNING | No such comm: 62b80460-16a9-45b3-ba29-789273c86737
[I 2022-08-12 12:08:41.140 ServerApp] Restoring connection for dbceacae-2852-4a3f-80ee-0c8cc011c227:2f28c86c-3fce-4d7d-8964-0ccd766721eb
[IPKernelApp] ERROR | No such comm target registered: jupyter.widget.control
[IPKernelApp] WARNING | No such comm: cc2e4267-a091-42f1-ab2a-58b834cf4aa9
[I 2022-08-12 12:08:47.840 ServerApp] Restoring connection for fefd0dd4-1a37-4b72-8cab-91e3d1b3c32e:65cce79a-47d7-427c-be03-76f2ac1084d8
[I 2022-08-12 12:08:50.405 ServerApp] Restoring connection for 81258831-5f98-4d35-802f-5362b7af0442:6a619003-7c85-42ad-a0ed-88b13ed678ac
[IPKernelApp] ERROR | No such comm target registered: jupyter.widget.control
[IPKernelApp] WARNING | No such comm: 7a79af21-e2d3-4839-9beb-b31f7900e083
[I 2022-08-12 12:08:57.265 ServerApp] Restoring connection for dd9889f9-54b5-4014-a95f-9758ae886487:d3ebb5d5-b16f-41ed-9cc9-2fc2d6520852
Terminated
[C 2022-08-12 12:09:58.306 ServerApp] received signal 15, stopping
[I 2022-08-12 12:09:58.359 ServerApp] Shutting down 3 extensions
[I 2022-08-12 12:09:58.359 ServerApp] Shutting down 8 kernels
[I 2022-08-12 12:09:58.359 ServerApp] Kernel shutdown: fefd0dd4-1a37-4b72-8cab-91e3d1b3c32e
[I 2022-08-12 12:09:58.360 ServerApp] Kernel shutdown: 4bbffea0-e14a-4ec5-8251-cc6350c16ac8
[I 2022-08-12 12:09:58.360 ServerApp] Kernel shutdown: dbceacae-2852-4a3f-80ee-0c8cc011c227
[I 2022-08-12 12:09:58.360 ServerApp] Kernel shutdown: dd9889f9-54b5-4014-a95f-9758ae886487
[I 2022-08-12 12:09:58.360 ServerApp] Kernel shutdown: a86a509c-88ea-490c-9cb2-7a0267114c55
[I 2022-08-12 12:09:58.361 ServerApp] Kernel shutdown: ce66ad7c-ac32-456a-ae88-464d15e0a83e
[I 2022-08-12 12:09:58.361 ServerApp] Kernel shutdown: 66be769d-c0c4-4f6c-90b2-b12272b9b510
[I 2022-08-12 12:09:58.361 ServerApp] Kernel shutdown: 81258831-5f98-4d35-802f-5362b7af0442
[I 2022-08-12 12:10:00.974 ServerApp] Shutting down 0 terminals
